artifact_uri: file:/home/vboxuser/mlprojects/sample/notebooks/mlflow/0/b86c237bde36432c80dc534bc2baef09/artifacts
end_time: 1692854505696
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b86c237bde36432c80dc534bc2baef09
run_uuid: b86c237bde36432c80dc534bc2baef09
source_name: ''
source_type: 4
source_version: ''
start_time: 1692854505398
status: 3
tags: []
user_id: vboxuser
